name: Dancemore
favicon: null
layout_spectrum: 0.2572
typography_spectrum: 0.53095
title: Dancemore
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3220084875356406
  lightness: 0.03689125902019441
  saturation: 0.04389349347911775
  rhythmicContrast: 0.24367148289456964
purpose: []
